default: &default
  adapter: mysql
  pool: 5
  timeout: 5000
  host: db.dev
  username: root
  password: password
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: v3_web_dev

# cucumber:
#   <<: *test
