default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  host: db.dev
  username: root
  password: password
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: v6_web_dev

test:
  <<: *default
  database: v6_web_test